### ISSUE TITLE
Changed diagnostics output

### ISSUE THREAD

**Issue by danielnowakowski** [palantir/python-language-server#441] opened 2018-10-18 11:57 UTC
I used version 0.14.0 of the server before and for one of files I was receiving diagnostic output:
```
code: "E128"
message: "E128 continuation line under-indented for visual indent"
range:
	end:
		character: 26
		line: 6
	start:
		character: 4
		line: 6
severity: 2
source: "pycodestyle"

```

I've switched to version 0.21.1 of the server and for exactly the same file I'm receiving:
```
code: "E128"
message: "E128 14"
range:
	end:
		character: 26
		line: 6
	start:
		character: 4
		line: 6
severity: 2
source: "pycodestyle"
```

The difference between these diagnostics is message. It seems to be a bit strange in version 0.21.1 of the server.

**Comment by danielnowakowski** [comment] 2018-11-08 10:00
Hi,

Is anything known in this topic?

**Comment by ccordoba12** [comment] 2019-08-24 08:42
Closing as a duplicate of #342.

**Closed as completed by ccordoba12** 2019-08-24 08:42 UTC
