### ISSUE TITLE
Running pyls with python -m pyls

### ISSUE THREAD

**Issue by max-sixty** [palantir/python-language-server#258] opened 2018-02-14 02:15 UTC
Thank you for the superb package!

Is there a way to specify which version of python you want to run `pyls` under?

I've tried running `python2 -m pyls`, which is what I do for pytest, but that didn't seem to work

**Comment by gatesn** [comment] 2018-02-20 11:55
What do you mean that didn't seem to work?

**Comment by max-sixty** [comment] 2018-02-28 14:10
It exits immediately, after printing a warning (the warning is nothing to do with `pyls` tbc:

```
 ~  python2 -m pyls                                                                                                                                                                    
/usr/local/lib/python2.7/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
# exit
```

Do you see something different?

**Comment by gatesn** [comment] 2018-03-25 09:09
It seems this might be due to your Pandas installation. Can you run `pip install -U pandas` and then try again with debug logs? `pyls -vvv`

**Comment by max-sixty** [comment] 2018-03-25 20:36
TBC, my concern here isn't anything to do with the pandas warning, but by `pyls` exiting.

Though after upgrading pandas the exiting problem persists:


Works when called normally
```
pyls -vvv                                                                          
/usr/local/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
2018-03-25 16:30:01,729 UTC - INFO - pyls.python_ls - Starting PythonLanguageServer IO language server
```

Doesn't work when called with `python2 -m`
```
python2 -m pyls                                              
(Namespace(a=None, b=None), [])
(Namespace(a=None, b=None, c=None), [])
/usr/local/lib/python2.7/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
# exits
```

**Comment by mcepl** [comment] 2018-04-20 09:31
Try ``python2 ~/.local/bin/pyls`` (or wherever you have pyls script installed). You will most likely also have to install ``python-language-server`` for the appropriate version of python (``python2 -mpip install --user python-language-server`` or something; in case you have pyls installed system-wide, you have to use ``sudo`` and don't use ``--user``).

**Comment by max-sixty** [comment] 2018-04-20 16:23
Right, I have installed in both places (otherwise it would raise)

**Comment by mcepl** [comment] 2018-04-21 07:50
@maxim-lian and does it work now?

**Comment by max-sixty** [comment] 2018-04-21 15:35
Thanks for the responses

I just tried it on `python-language-server==0.17.2`. Running either `python2 -m pyls` or `python3 -m pyls`, it starts and exists 9.2s and 5.9s later respectively.

Running `pyls` works as expected - no exiting shortly after.
And so does `python2 ~/.local/bin/pyls` and `python3 ~/.local/bin/pyls` 

So it's not actually anything to do with python2 / python3 - it's when run with `python -m` where it doesn't work

**Comment by mcepl** [comment] 2018-04-21 19:31
So, I guess, this bug can be closed?

**Comment by max-sixty** [comment] 2018-04-21 20:15
I changed the title to refer to running from `python -m` (which is the canonical way of running python modules with a specific python, and works for every other module I've encountered)

That said, no offense taken if this isn't important and you'd like to close

Thanks again for working through the issues with me

**Comment by mcepl** [comment] 2018-04-21 23:03
I cannot close this bug, i am not an owner of the package.

**Comment by gatesn** [comment] 2018-04-23 11:05
Seems odd that it works one way and not the other. I can look into what the differences might be.

**Comment by gatesn** [comment] 2018-05-04 23:00
So I can't reproduce your issue, but I do note that `pyls` waits for stdin, whereas `python -m pyls` exits immediately. I will look into this difference.

**Closed as completed** 2018-05-09 13:34 UTC
