### ISSUE TITLE
LSP :: TypeError: py__call__() missing 1 required positional argument: 'arguments'

### ISSUE THREAD

**Issue by MaT1g3R** [palantir/python-language-server#724] opened 2020-01-03 06:12 UTC
# Description
When I try to complete this code:
```python
import subprocess
subprocess.run([]). <-- error happens here at the dot
```

I get the below exception:
```
LSP :: TypeError: py__call__() missing 1 required positional argument: 'arguments'
```

# Versions

Python version: 3.8.1

Python language server versions:
```
python-language-server==0.31.4
pyls-black==0.4.4
```

LSP client: emacs lsp-mode

**Comment by ppwwyyxx** [comment] 2020-01-06 08:50
should be fixed in https://github.com/davidhalter/jedi/issues/1468

**Comment by ccordoba12** [comment] 2020-01-06 13:52
Closing then.

**Closed as completed by ccordoba12** 2020-01-06 13:52 UTC

**Comment by ghost** [comment] 2020-05-02 07:22
@ccordoba12  Can I bump this to actually integrate this into pyls / spyder? this fix requires jedi 0.16 or 0.17 at the moment, which is incompatible. This error makes code completion only ever work for a short time before crashing (fortunately spyder keeps on going at least).

**Comment by ccordoba12** [comment] 2020-05-02 15:48
@athompson6735, thanks a lot for letting us know about it! Does this happen when `pyls-black` is also installed? Or does that not matter?

**Comment by ccordoba12** [comment] 2020-05-02 15:55
Also, we'll try to fix that in 4.1.4, to be released in a couple of weeks.

**Comment by ghost** [comment] 2020-05-02 18:15
My solution  was to manually edit the fix into my install of jedi 0.15.2. I was not aware of `pyls-black`. I'll give it a shot.

**Comment by ghost** [comment] 2020-05-02 19:08
@ccordoba12 unfortunately, `pyls-black` made no difference. Here's my setup to maybe reproduce:

<details>
<summary>install dependencies (spyder 4.1.2)</summary>

```
# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.2 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```
</details>

<details>
<summary>completion and linting preferences:</summary>

```
Completion:
    Enable code completion: True
    Show completion details: True (after 500ms)
    Show completions on the fly: True
    (after chars entered: 3, after 300ms)
    Enable code snippets: False
Linting:
    Enable basic linting: True
    underline errors and warnings: False
    Enable complexity linting: False
Introspection:
    Enable Go to Definition: True
    Follow imports: True
    Show calltips: True
    Enable hover hints: True
Code style:
    Enable code style linting: False
Docstring style:
    Enable docstring style linting: False
Advanced:
    Enable Kite: False
    Enable fallback completions: True
    Time to wait: 200ms
    Pyls server config:
        advanced settings: False
        module: pyls
        address: 127.0.0.1
```
</details>

Start a new file: and type slowly with time to allow completions to appear
```
import numpy as np
with open('somerandomfile.txt') as f:
    data = f.read()
```
The error (a syntax error) occurs on typing the period after `f` on the last line. After this, all warnings (imported but unused `np`) hide, and never come back. The syntax error also never clears even once the line is completely typed. If typed quickly, the error does not occur, so it seems to be the request for completion that kills it, not the identification of the syntax error (uneducated speculation). 

copying the new `jedi/inference/value/klass.py` from https://github.com/davidhalter/jedi/commit/9c4cd40b7edcced183b54d480289bf0be3196717 into my install of jedi 0.15.2 solves the problem.

**Comment by ccordoba12** [comment] 2020-05-02 23:43
Ok, thanks for the extra verification.
