### ISSUE TITLE
pyls crashes on macOS

### ISSUE THREAD

**Issue by BEFH** [palantir/python-language-server#308] opened 2018-03-25 13:33 UTC
I'm getting the following error when attempting to run pyls on my macOS computers:

```
/Users/bfh/anaconda/lib/python3.5/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
^C/Users/bfh/anaconda/lib/python3.5/site-packages/skimage/viewer/utils/core.py:10: UserWarning: Recommended matplotlib backend is `Agg` for full skimage.viewer functionality.
  warn("Recommended matplotlib backend is `Agg` for full "
2018-03-25 09:18:58.570 python[27155:5505496] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7ffae3d27740
2018-03-25 09:18:58.573 python[27155:5505496] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7ffae3d27740'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffb44262cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffc923d48d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffb44a7f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fffb4398755 ___forwarding___ + 1061
	4   CoreFoundation                      0x00007fffb43982a8 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x0000001d226e646f TkpInit + 383
	6   libtk8.6.dylib                      0x0000001d2263f21e Initialize + 2622
	7   _tkinter.cpython-35m-darwin.so      0x0000001d22465a06 _tkinter_create + 1174
	8   python                              0x0000000104c140be PyCFunction_Call + 62
	9   python                              0x0000000104cdbf30 PyEval_EvalFrameEx + 18640
	10  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	11  python                              0x0000000104be10ca function_call + 106
	12  python                              0x0000000104b9d5a5 PyObject_Call + 69
	13  python                              0x0000000104bc00e4 method_call + 148
	14  python                              0x0000000104b9d5a5 PyObject_Call + 69
	15  python                              0x0000000104c39f15 slot_tp_init + 117
	16  python                              0x0000000104c3e5c1 type_call + 209
	17  python                              0x0000000104b9d5a5 PyObject_Call + 69
	18  python                              0x0000000104cdc1db PyEval_EvalFrameEx + 19323
	19  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	20  python                              0x0000000104cd03a5 builtin_exec + 341
	21  python                              0x0000000104c140be PyCFunction_Call + 62
	22  python                              0x0000000104cdcf84 PyEval_EvalFrameEx + 22820
	23  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	24  python                              0x0000000104cdc26e PyEval_EvalFrameEx + 19470
	25  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	26  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	27  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	28  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	29  python                              0x0000000104be10ca function_call + 106
	30  python                              0x0000000104b9f972 _PyObject_CallMethodIdObjArgs + 482
	31  python                              0x0000000104d06310 PyImport_ImportModuleLevelObject + 2352
	32  python                              0x0000000104ccefb5 builtin___import__ + 149
	33  python                              0x0000000104c140ff PyCFunction_Call + 127
	34  python                              0x0000000104cdbf30 PyEval_EvalFrameEx + 18640
	35  python                              0x0000000104bd6064 gen_send_ex + 148
	36  python                              0x0000000104cde611 PyEval_EvalFrameEx + 28593
	37  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	38  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	39  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	40  python                              0x0000000104cce998 builtin___build_class__ + 408
	41  python                              0x0000000104c140ff PyCFunction_Call + 127
	42  python                              0x0000000104cdbf30 PyEval_EvalFrameEx + 18640
	43  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	44  python                              0x0000000104cd03a5 builtin_exec + 341
	45  python                              0x0000000104c140be PyCFunction_Call + 62
	46  python                              0x0000000104cdcf84 PyEval_EvalFrameEx + 22820
	47  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	48  python                              0x0000000104cdc26e PyEval_EvalFrameEx + 19470
	49  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	50  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	51  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	52  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	53  python                              0x0000000104be10ca function_call + 106
	54  python                              0x0000000104b9f972 _PyObject_CallMethodIdObjArgs + 482
	55  python                              0x0000000104d06310 PyImport_ImportModuleLevelObject + 2352
	56  python                              0x0000000104ccefb5 builtin___import__ + 149
	57  python                              0x0000000104c140ff PyCFunction_Call + 127
	58  python                              0x0000000104b9d5a5 PyObject_Call + 69
	59  python                              0x0000000104cded83 PyEval_EvalFrameEx + 30499
	60  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	61  python                              0x0000000104cd03a5 builtin_exec + 341
	62  python                              0x0000000104c140be PyCFunction_Call + 62
	63  python                              0x0000000104cdcf84 PyEval_EvalFrameEx + 22820
	64  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	65  python                              0x0000000104cdc26e PyEval_EvalFrameEx + 19470
	66  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	67  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	68  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	69  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	70  python                              0x0000000104be10ca function_call + 106
	71  python                              0x0000000104b9f972 _PyObject_CallMethodIdObjArgs + 482
	72  python                              0x0000000104d06310 PyImport_ImportModuleLevelObject + 2352
	73  python                              0x0000000104ccefb5 builtin___import__ + 149
	74  python                              0x0000000104c140ff PyCFunction_Call + 127
	75  python                              0x0000000104b9d5a5 PyObject_Call + 69
	76  python                              0x0000000104cded83 PyEval_EvalFrameEx + 30499
	77  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	78  python                              0x0000000104cd03a5 builtin_exec + 341
	79  python                              0x0000000104c140be PyCFunction_Call + 62
	80  python                              0x0000000104cdcf84 PyEval_EvalFrameEx + 22820
	81  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	82  python                              0x0000000104cdc26e PyEval_EvalFrameEx + 19470
	83  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	84  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	85  python                              0x0000000104cdc021 PyEval_EvalFrameEx + 18881
	86  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	87  python                              0x0000000104be10ca function_call + 106
	88  python                              0x0000000104b9f972 _PyObject_CallMethodIdObjArgs + 482
	89  python                              0x0000000104d06310 PyImport_ImportModuleLevelObject + 2352
	90  python                              0x0000000104ccefb5 builtin___import__ + 149
	91  python                              0x0000000104c140ff PyCFunction_Call + 127
	92  python                              0x0000000104b9d5a5 PyObject_Call + 69
	93  python                              0x0000000104cded83 PyEval_EvalFrameEx + 30499
	94  python                              0x0000000104cd5fdf _PyEval_EvalCodeWithName + 335
	95  python                              0x0000000104d287b8 PyRun_FileExFlags + 248
	96  python                              0x0000000104d27f4e PyRun_SimpleFileExFlags + 382
	97  python                              0x0000000104d4cdc6 Py_Main + 3606
	98  python                              0x0000000104b8e301 main + 497
	99  libdyld.dylib                       0x0000000104efb235 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
fish: 'pyls' terminated by signal SIGABRT (Abort)
```

**Comment by gatesn** [comment] 2018-03-25 14:52
This seems to be caused by some use of matplotlib I think... Triggered by pre-loading this set of modules: https://github.com/palantir/python-language-server/blob/develop/pyls/workspace.py#L41

I'm going to remove module pre-loading, or at least make it configurable for now.

**Comment by BEFH** [comment] 2018-03-25 15:25
Thanks! That's what I thought was going on, but I saw an old bug report where they claimed to have fixed it. ¯\\\_(ツ)_/¯

**Comment by haberdashPI** [comment] 2018-07-12 12:34
Getting the same error, just wanted to ping this and see if there's any progress.

**Comment by jiahuijiang** [comment] 2018-11-23 13:01
Hey guys, 0.21.3 is released with the checking parent process aliveness turned off by default. Closing this out now. Let us know if you are still encountering issues!

**Closed as completed by jiahuijiang** 2018-11-23 13:01 UTC
