### ISSUE TITLE
pyls: error: no such option: --log-file

### ISSUE THREAD

**Issue by evandrocoan** [palantir/python-language-server#242] opened 2018-01-25 18:04 UTC
When initializing the server with the option `--log-file`:
```javascript
"pyls":
{
	"command":
	[
		"pyls",
		"-vv",
		"--log-file",
		"F:/SublimeText/debug2.txt"
	],
	"enabled": true,
}
```

We got the error:
```
server: 
server: pyls: error: no such option: --log-file
server: Usage: pydocstyle [options] [<file|dir>...]
```

**Comment by gatesn** [comment] 2018-01-25 22:56
Duplicate of #228

**Closed as completed by gatesn** 2018-01-25 22:56 UTC
